apiVersion: v2
name: prometheus-grafana
description: A Helm chart that deploys prometheus and grafana
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 70.4.2
    repository: https://prometheus-community.github.io/helm-charts
