kube-prometheus-stack:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: ocr-model
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        scheme: 'http'
        static_configs:
          - targets: ["model-server.default.svc.cluster.local:80"]