argo-cd:
  configs:
    cm:
      application.resourceTrackingMethod: annotation
  dex:
    enabled: false
  notifications:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  controller:
    resources:
      requests:
        cpu: 50m
        memory: 300Mi
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 50%
  server:
    pdb:
      enabled: true
      minAvailable: 50%
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 15Mi
    replicas: 1
  redis-ha:
    podDisruptionBudget:
      minAvailable: 50%
    haproxy:
      podDisruptionBudget:
        minAvailable: 50%

  repoServer:
    replicas: 1
    pdb:
      enabled: true
      minAvailable: 50%
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
  applicationSet:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    replicaCount: 1
    pdb:
      enabled: true
      minAvailable: 50%
  redis:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
