{
 "title": "OCR-Model-Monitoring-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "1m Average of Memory Usage of Model Server (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"model-server\", pod=~\"model-server-.*\"}[1m])) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1m Average of CPU Usage of Model Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"model-server\", pod=~\"model-server-.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1Minute Average of Request PreProcess Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(rate(request_preprocess_seconds_sum{model_name=\"ocr-model\"}[1m])) / avg(rate(request_preprocess_seconds_count{model_name=\"ocr-model\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1Minute Average of Prediction Time of Requests (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(request_predict_seconds_sum{model_name=\"ocr-model\"}[1m])) / avg(rate(request_predict_seconds_count{model_name=\"ocr-model\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1Minute Average of Request PostProcess Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg(rate(request_postprocess_seconds_sum{model_name=\"ocr-model\"}[1m])) / avg(rate(request_postprocess_seconds_count{model_name=\"ocr-model\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}