service-common-chart:
  name: api-gateway
  replicaCount: 1

  image:
    repository: roodocker7298/api-gateway
    tag: 5c0d663

  containerPort: 8001

  env:
    - name: KSERVE_URL
      value: "http://model-server.model-server.svc.cluster.local/v2/models/ocr-model/infer"

  service:
    portName: http
    port: 8080
    type: ClusterIP
