apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ocr-model-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-grafana
spec:
  selector:
    matchLabels:
      app: model-server
  namespaceSelector:
    matchNames:
      - model-server
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
